[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18" # Specify a recent LTS Node.js version

# Standard SPA redirect rule
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
